/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.GUICadastrar;
public class GUIHomeSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form GUIHome
     */
    public GUIHomeSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        painelPrinciapal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrarMembros = new javax.swing.JMenu();
        menuCadastrarMembro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuCarta = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuEditarMembro = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuMembros2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItemMembro2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADELPHOS - IEADTC Guaraciaba do Norte");

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));

        jLabel1.setBackground(new java.awt.Color(187, 187, 187));
        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 240));
        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Secretario:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 240));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADELPHOS - Sistema Eclesiástico");

        jLabel4.setBackground(new java.awt.Color(255, 255, 240));
        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Secretaria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout painelPrinciapalLayout = new javax.swing.GroupLayout(painelPrinciapal);
        painelPrinciapal.setLayout(painelPrinciapalLayout);
        painelPrinciapalLayout.setHorizontalGroup(
            painelPrinciapalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelPrinciapalLayout.setVerticalGroup(
            painelPrinciapalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        menuCadastrarMembros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registro.png"))); // NOI18N
        menuCadastrarMembros.setText("Cadastrar");
        menuCadastrarMembros.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        menuCadastrarMembro.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        menuCadastrarMembro.setText("Membro");
        menuCadastrarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarMembroActionPerformed(evt);
            }
        });
        menuCadastrarMembros.add(menuCadastrarMembro);
        menuCadastrarMembros.add(jSeparator1);

        jMenuItem8.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuItem8.setText("Congregação");
        menuCadastrarMembros.add(jMenuItem8);
        menuCadastrarMembros.add(jSeparator5);

        menuCarta.setText("Carta");
        menuCarta.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuItem1.setText("Recomendação");
        menuCarta.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuItem2.setText("Mudança");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuCarta.add(jMenuItem2);

        menuCadastrarMembros.add(menuCarta);

        jMenuBar1.add(menuCadastrarMembros);

        menuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cadastro.png"))); // NOI18N
        menuEditar.setText("Editar");
        menuEditar.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        menuEditarMembro.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        menuEditarMembro.setText("Membro");
        menuEditarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarMembroActionPerformed(evt);
            }
        });
        menuEditar.add(menuEditarMembro);
        menuEditar.add(jSeparator2);

        jMenu2.setText("Carta");
        jMenu2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        jMenuItem3.setText("Recomendação");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Mudança");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        menuEditar.add(jMenu2);

        jMenuBar1.add(menuEditar);

        menuMembros2.setText("Vizualizar");
        menuMembros2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuItem7.setText("Cartão de Membro");
        menuMembros2.add(jMenuItem7);
        menuMembros2.add(jSeparator3);

        menuItemMembro2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        menuItemMembro2.setText("Membro");
        menuMembros2.add(menuItemMembro2);
        menuMembros2.add(jSeparator4);

        jMenu3.setText("Carta");
        jMenu3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuItem5.setText("Recomendação");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuItem6.setText("Mudança");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        menuMembros2.add(jMenu3);

        jMenuBar1.add(menuMembros2);

        menuSobre.setText("Sobre");
        menuSobre.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelPrinciapal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelPrinciapal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuEditarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarMembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEditarMembroActionPerformed

    private void menuCadastrarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarMembroActionPerformed
       
        GUICadastrar membro = new GUICadastrar();
        painelPrinciapal.add (membro);
        membro.show();
                
    }//GEN-LAST:event_menuCadastrarMembroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHomeSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHomeSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHomeSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHomeSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHomeSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem menuCadastrarMembro;
    private javax.swing.JMenu menuCadastrarMembros;
    private javax.swing.JMenu menuCarta;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuEditarMembro;
    private javax.swing.JMenuItem menuItemMembro2;
    private javax.swing.JMenu menuMembros2;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JPanel painelPrinciapal;
    // End of variables declaration//GEN-END:variables
}
